<?php
// This file is automatically generated. Do not edit directly.
if ( ! defined( 'ABSPATH' ) ) {
	die( 'Silence is golden.' );
}

return array(
	'arrow-down-left'     => array(
		'label'     => _x( 'Arrow Down Left', 'icon label' ),
		'file_path' => 'arrow-down-left.svg',
	),
	'arrow-down-right'    => array(
		'label'     => _x( 'Arrow Down Right', 'icon label' ),
		'file_path' => 'arrow-down-right.svg',
	),
	'arrow-down'          => array(
		'label'     => _x( 'Arrow Down', 'icon label' ),
		'file_path' => 'arrow-down.svg',
	),
	'arrow-left'          => array(
		'label'     => _x( 'Arrow Left', 'icon label' ),
		'file_path' => 'arrow-left.svg',
	),
	'arrow-right'         => array(
		'label'     => _x( 'Arrow Right', 'icon label' ),
		'file_path' => 'arrow-right.svg',
	),
	'arrow-up-left'       => array(
		'label'     => _x( 'Arrow Up Left', 'icon label' ),
		'file_path' => 'arrow-up-left.svg',
	),
	'arrow-up-right'      => array(
		'label'     => _x( 'Arrow Up Right', 'icon label' ),
		'file_path' => 'arrow-up-right.svg',
	),
	'arrow-up'            => array(
		'label'     => _x( 'Arrow Up', 'icon label' ),
		'file_path' => 'arrow-up.svg',
	),
	'at-symbol'           => array(
		'label'     => _x( 'At Symbol (@)', 'icon label' ),
		'file_path' => 'at-symbol.svg',
	),
	'audio'               => array(
		'label'     => _x( 'Audio', 'icon label' ),
		'file_path' => 'audio.svg',
	),
	'bell'                => array(
		'label'     => _x( 'Bell', 'icon label' ),
		'file_path' => 'bell.svg',
	),
	'block-default'       => array(
		'label'     => _x( 'Block Default', 'icon label' ),
		'file_path' => 'block-default.svg',
	),
	'block-meta'          => array(
		'label'     => _x( 'Block Meta', 'icon label' ),
		'file_path' => 'block-meta.svg',
	),
	'block-table'         => array(
		'label'     => _x( 'Block Table', 'icon label' ),
		'file_path' => 'block-table.svg',
	),
	'calendar'            => array(
		'label'     => _x( 'Calendar', 'icon label' ),
		'file_path' => 'calendar.svg',
	),
	'capture-photo'       => array(
		'label'     => _x( 'Capture Photo', 'icon label' ),
		'file_path' => 'capture-photo.svg',
	),
	'capture-video'       => array(
		'label'     => _x( 'Capture Video', 'icon label' ),
		'file_path' => 'capture-video.svg',
	),
	'cart'                => array(
		'label'     => _x( 'Cart', 'icon label' ),
		'file_path' => 'cart.svg',
	),
	'category'            => array(
		'label'     => _x( 'Category', 'icon label' ),
		'file_path' => 'category.svg',
	),
	'caution'             => array(
		'label'     => _x( 'Caution', 'icon label' ),
		'file_path' => 'caution.svg',
	),
	'chart-bar'           => array(
		'label'     => _x( 'Chart Bar', 'icon label' ),
		'file_path' => 'chart-bar.svg',
	),
	'check'               => array(
		'label'     => _x( 'Check', 'icon label' ),
		'file_path' => 'check.svg',
	),
	'chevron-down'        => array(
		'label'     => _x( 'Chevron Down', 'icon label' ),
		'file_path' => 'chevron-down.svg',
	),
	'chevron-down-small'  => array(
		'label'     => _x( 'Chevron Down Small', 'icon label' ),
		'file_path' => 'chevron-down-small.svg',
	),
	'chevron-left'        => array(
		'label'     => _x( 'Chevron Left', 'icon label' ),
		'file_path' => 'chevron-left.svg',
	),
	'chevron-left-small'  => array(
		'label'     => _x( 'Chevron Left Small', 'icon label' ),
		'file_path' => 'chevron-left-small.svg',
	),
	'chevron-right'       => array(
		'label'     => _x( 'Chevron Right', 'icon label' ),
		'file_path' => 'chevron-right.svg',
	),
	'chevron-right-small' => array(
		'label'     => _x( 'Chevron Right Small', 'icon label' ),
		'file_path' => 'chevron-right-small.svg',
	),
	'chevron-up'          => array(
		'label'     => _x( 'Chevron Up', 'icon label' ),
		'file_path' => 'chevron-up.svg',
	),
	'chevron-up-down'     => array(
		'label'     => _x( 'Chevron Up Down', 'icon label' ),
		'file_path' => 'chevron-up-down.svg',
	),
	'chevron-up-small'    => array(
		'label'     => _x( 'Chevron Up Small', 'icon label' ),
		'file_path' => 'chevron-up-small.svg',
	),
	'comment'             => array(
		'label'     => _x( 'Comment', 'icon label' ),
		'file_path' => 'comment.svg',
	),
	'cover'               => array(
		'label'     => _x( 'Cover', 'icon label' ),
		'file_path' => 'cover.svg',
	),
	'create'              => array(
		'label'     => _x( 'Create', 'icon label' ),
		'file_path' => 'create.svg',
	),
	'desktop'             => array(
		'label'     => _x( 'Desktop', 'icon label' ),
		'file_path' => 'desktop.svg',
	),
	'download'            => array(
		'label'     => _x( 'Download', 'icon label' ),
		'file_path' => 'download.svg',
	),
	'drawer-left'         => array(
		'label'     => _x( 'Drawer Left', 'icon label' ),
		'file_path' => 'drawer-left.svg',
	),
	'drawer-right'        => array(
		'label'     => _x( 'Drawer Right', 'icon label' ),
		'file_path' => 'drawer-right.svg',
	),
	'envelope'            => array(
		'label'     => _x( 'Envelope', 'icon label' ),
		'file_path' => 'envelope.svg',
	),
	'error'               => array(
		'label'     => _x( 'Error', 'icon label' ),
		'file_path' => 'error.svg',
	),
	'external'            => array(
		'label'     => _x( 'External', 'icon label' ),
		'file_path' => 'external.svg',
	),
	'file'                => array(
		'label'     => _x( 'File', 'icon label' ),
		'file_path' => 'file.svg',
	),
	'gallery'             => array(
		'label'     => _x( 'Gallery', 'icon label' ),
		'file_path' => 'gallery.svg',
	),
	'group'               => array(
		'label'     => _x( 'Group', 'icon label' ),
		'file_path' => 'group.svg',
	),
	'heading'             => array(
		'label'     => _x( 'Heading', 'icon label' ),
		'file_path' => 'heading.svg',
	),
	'help'                => array(
		'label'     => _x( 'Help', 'icon label' ),
		'file_path' => 'help.svg',
	),
	'home'                => array(
		'label'     => _x( 'Home', 'icon label' ),
		'file_path' => 'home.svg',
	),
	'image'               => array(
		'label'     => _x( 'Image', 'icon label' ),
		'file_path' => 'image.svg',
	),
	'info'                => array(
		'label'     => _x( 'Info', 'icon label' ),
		'file_path' => 'info.svg',
	),
	'key'                 => array(
		'label'     => _x( 'Key', 'icon label' ),
		'file_path' => 'key.svg',
	),
	'language'            => array(
		'label'     => _x( 'Language', 'icon label' ),
		'file_path' => 'language.svg',
	),
	'map-marker'          => array(
		'label'     => _x( 'Map Marker', 'icon label' ),
		'file_path' => 'map-marker.svg',
	),
	'menu'                => array(
		'label'     => _x( 'Menu', 'icon label' ),
		'file_path' => 'menu.svg',
	),
	'mobile'              => array(
		'label'     => _x( 'Mobile', 'icon label' ),
		'file_path' => 'mobile.svg',
	),
	'more-horizontal'     => array(
		'label'     => _x( 'More Horizontal', 'icon label' ),
		'file_path' => 'more-horizontal.svg',
	),
	'more-vertical'       => array(
		'label'     => _x( 'More Vertical', 'icon label' ),
		'file_path' => 'more-vertical.svg',
	),
	'next'                => array(
		'label'     => _x( 'Next', 'icon label' ),
		'file_path' => 'next.svg',
	),
	'paragraph'           => array(
		'label'     => _x( 'Paragraph', 'icon label' ),
		'file_path' => 'paragraph.svg',
	),
	'payment'             => array(
		'label'     => _x( 'Payment', 'icon label' ),
		'file_path' => 'payment.svg',
	),
	'pencil'              => array(
		'label'     => _x( 'Pencil', 'icon label' ),
		'file_path' => 'pencil.svg',
	),
	'people'              => array(
		'label'     => _x( 'People', 'icon label' ),
		'file_path' => 'people.svg',
	),
	'plus'                => array(
		'label'     => _x( 'Plus', 'icon label' ),
		'file_path' => 'plus.svg',
	),
	'plus-circle'         => array(
		'label'     => _x( 'Plus Circle', 'icon label' ),
		'file_path' => 'plus-circle.svg',
	),
	'previous'            => array(
		'label'     => _x( 'Previous', 'icon label' ),
		'file_path' => 'previous.svg',
	),
	'published'           => array(
		'label'     => _x( 'Published', 'icon label' ),
		'file_path' => 'published.svg',
	),
	'quote'               => array(
		'label'     => _x( 'Quote', 'icon label' ),
		'file_path' => 'quote.svg',
	),
	'receipt'             => array(
		'label'     => _x( 'Receipt', 'icon label' ),
		'file_path' => 'receipt.svg',
	),
	'rss'                 => array(
		'label'     => _x( 'RSS', 'icon label' ),
		'file_path' => 'rss.svg',
	),
	'scheduled'           => array(
		'label'     => _x( 'Scheduled', 'icon label' ),
		'file_path' => 'scheduled.svg',
	),
	'search'              => array(
		'label'     => _x( 'Search', 'icon label' ),
		'file_path' => 'search.svg',
	),
	'settings'            => array(
		'label'     => _x( 'Settings', 'icon label' ),
		'file_path' => 'settings.svg',
	),
	'shadow'              => array(
		'label'     => _x( 'Shadow', 'icon label' ),
		'file_path' => 'shadow.svg',
	),
	'share'               => array(
		'label'     => _x( 'Share', 'icon label' ),
		'file_path' => 'share.svg',
	),
	'shield'              => array(
		'label'     => _x( 'Shield', 'icon label' ),
		'file_path' => 'shield.svg',
	),
	'shuffle'             => array(
		'label'     => _x( 'Shuffle', 'icon label' ),
		'file_path' => 'shuffle.svg',
	),
	'star-empty'          => array(
		'label'     => _x( 'Star Empty', 'icon label' ),
		'file_path' => 'star-empty.svg',
	),
	'star-filled'         => array(
		'label'     => _x( 'Star Filled', 'icon label' ),
		'file_path' => 'star-filled.svg',
	),
	'star-half'           => array(
		'label'     => _x( 'Star Half', 'icon label' ),
		'file_path' => 'star-half.svg',
	),
	'store'               => array(
		'label'     => _x( 'Store', 'icon label' ),
		'file_path' => 'store.svg',
	),
	'styles'              => array(
		'label'     => _x( 'Styles', 'icon label' ),
		'file_path' => 'styles.svg',
	),
	'symbol'              => array(
		'label'     => _x( 'Symbol', 'icon label' ),
		'file_path' => 'symbol.svg',
	),
	'symbol-filled'       => array(
		'label'     => _x( 'Symbol Filled', 'icon label' ),
		'file_path' => 'symbol-filled.svg',
	),
	'table'               => array(
		'label'     => _x( 'Table', 'icon label' ),
		'file_path' => 'table.svg',
	),
	'tablet'              => array(
		'label'     => _x( 'Tablet', 'icon label' ),
		'file_path' => 'tablet.svg',
	),
	'tag'                 => array(
		'label'     => _x( 'Tag', 'icon label' ),
		'file_path' => 'tag.svg',
	),
	'tip'                 => array(
		'label'     => _x( 'Tip', 'icon label' ),
		'file_path' => 'tip.svg',
	),
	'upload'              => array(
		'label'     => _x( 'Upload', 'icon label' ),
		'file_path' => 'upload.svg',
	),
	'verse'               => array(
		'label'     => _x( 'Verse', 'icon label' ),
		'file_path' => 'verse.svg',
	),
);
